name: projeto-base

services:
  db:
    image: postgres:16-alpine
    container_name: projeto_base_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: projetobase
    ports:
      - "5435:5432"
    volumes:
      - projeto_base_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: projeto_base_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ../backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
      - /var/run/docker.sock:/var/run/docker.sock:ro

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: projeto_base_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  projeto_base_pg_data:
